services:
# postgres:
#   image: postgres
#   container_name: postgres-sql-bsn
#   environment:
#     POSTGRES_USER: username
#     POSTGRES_PASSWORD: password
#     PGDATA: /var/lib/postgresql/data
#     POSTGRES_DB: book_social_network
#   volumes:
#     - postgres:/data/postgres
#   ports:
#     - 5433:5432
#   networks:
#     - spring-demo
#   restart: unless-stopped
#   healthcheck:
#     test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
#     interval: 10s
#     timeout: 3s
#     retries: 3

 mail-dev:
   container_name: mail-dev-bsn
   image: maildev/maildev:latest
   ports:
     - 1080:1080
     - 1025:1025

 bsn-api:
   container_name: bsn-api
   image: ${DOCKERHUB_USERNAME}/bsn:latest
   environment:
     DB_URL: ${DB_URL}
     USER_NAME: ${USER_NAME}
     PASSWORD: ${PASSWORD}
   ports:
     - 8088:8088
   networks:
     - spring-demo

 bsn-ui:
    container_name: bsn-ui
    image: ${DOCKERHUB_USERNAME}/bsn-ui:latest
    ports:
      - 8080:80
    networks:
      - spring-demo

networks:
 spring-demo:
   driver: bridge
   
volumes:
 postgres:
   driver: local

