services:
 postgres:
   container_name: postgres-sql-bsn
   image: postgres
   environment:
     POSTGRES_USER: username
     POSTGRES_PASSWORD: password
     PGDATA: /var/lib/postgresql/data
     POSTGRES_DB: book_social_network
   volumes:
     - postgres:/data/postgres
   ports:
     - 5440:5432
   networks:
     - spring-demo
   restart: unless-stopped

 mail-dev:
   container_name: mail-dev-bsn
   image: maildev/maildev
   ports:
     - 1080:1080
     - 1025:1025

 bsn-api:
   container_name: bsn-api
   image: bsn/bsn
  # #  we can pass environment variable if we want, but since we have already passed default values in dockerfile itself so here is not must to pass.
  #  environment:
  #   - DB_URL
  #   - ACTIVE_PROFILE
  #   - APP_VERSION
   ports:
     - 8088:8088
   networks:
     - spring-demo
   depends_on:
      postgres:
        condition: service_healthy

 bsn-ui:
    container_name: bsn-ui
    image: bsn/bsn-ui
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      bsn-api:
        condition: service_healthy

networks:
 spring-demo:
   driver: bridge
   
volumes:
 postgres:
   driver: local

