services:
# postgres:
#   image: postgres
#   container_name: postgres-sql-bsn
#   environment:
#     POSTGRES_USER: username
#     POSTGRES_PASSWORD: password
#     PGDATA: /var/lib/postgresql/data
#     POSTGRES_DB: book_social_network
#   volumes:
#     - postgres:/data/postgres
#   ports:
#     - 5433:5432
#   networks:
#     - spring-demo
#   restart: unless-stopped
#   healthcheck:
#     test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
#     interval: 10s
#     timeout: 3s
#     retries: 3

 mail-dev:
   container_name: mail-dev-bsn
   image: maildev/maildev
   ports:
     - 1080:1080
     - 1025:1025

 bsn-api:
   container_name: bsn-api
   image: ${DOCKERHUB_USERNAME}/bsn
#   env_file:
#     - book-network-backend/.env
  # #  we can pass environment variable if we want, but since we have already passed default values in dockerfile itself so here is not must to pass.
   environment:
     DB_URL: ${DB_URL}
     USER_NAME: ${USER_NAME}
     PASSWORD: ${PASSWORD}
#     - ACTIVE_PROFILE
#     - APP_VERSION
   ports:
     - 8088:8088
   networks:
     - spring-demo
#   depends_on:
#      postgres:
#        condition: service_healthy

 bsn-ui:
    container_name: bsn-ui
#    image: ${DOCKERHUB_USERNAME}/bsn-ui
    image: parthchamp17/bsn-ui:0.1.0
    ports:
      - 8080:80
    networks:
      - spring-demo
#    depends_on:
#      bsn-api:
#        condition: service_healthy

networks:
 spring-demo:
   driver: bridge
   
volumes:
 postgres:
   driver: local

